# Generated by Django 3.2.3 on 2021-05-27 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='static/app/images/', verbose_name='Картинка'),
        ),
    ]
