# Generated by Django 3.2.3 on 2021-05-30 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('surname', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('number', models.CharField(max_length=100, verbose_name='Номер телефона')),
                ('email', models.CharField(max_length=254, verbose_name='Почта')),
                ('text', models.TextField(verbose_name='Текст заявки')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('surname', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('image', models.ImageField(null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Картинка пользователя')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=254, verbose_name='Почта')),
            ],
        ),
    ]
